baseurl = "https://gorkemozlu.github.io"
title = "Gorkem Ozlu - Yet Another Cloud Native Blog"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Gorkem Ozlu"
  bio = "Gorkem Ozlu is Senior Tanzu Solution Engineer at VMware."
  avatar = "img/1597427326741.jpeg"

[Params]
  description = "Yet Another Cloud Native Blog" # Description of your site
  opengraph = true
  twitter_cards = true
  readmore = true # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "blog", "news"]
  dateformat = "2006-01-02"

[Params.logo]
  subtitle = "Yet Another Cloud Native Blog" # Logo subtitle
  title = "Gorkem Ozlu"
  image = "img/1597427326741.jpeg"

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "sidemenu","recent", "categories", "taglist","social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
[Params.widgets.social]
  # Enable parts of social widget
  linkedin = "bgorkemozlu"
  github = "gorkemozlu"
[Params.style.vars]
  themeBGColor = "#1B2A32"
  themeMainColor = "#314150" # Override main theme color
  themeWrpColor = "#23333C" # Override main theme color
  themeHeaderColor = "#314150"
  themeAColor = "#5BCEFF"
  highlightColor = "#5BCEFF"